version: 1

update_configs:
  - package_manager: javascript
    directory: "/"
    update_schedule: daily
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
  - package_manager: javascript
    directory: "/docs"
    update_schedule: weekly
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
