name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '35 4 * * 4' # weekly, on Thursday morning

env:
  CI: true

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 8
    - name: install dependencies
      run: npm ci
    - name: lint js
      run: npm run lint:js
    - name: lint hbs
      run: npm run lint:hbs
    - name: test
      run: npm test
      env:
        PERCY_TOKEN: ${{secrets.percy_token}}

  test-floating:
    name: Floating Dependencies
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    needs: test
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install dependencies
      run: npm install --no-package-lock
    - name: test
      run: npm test

  try-scenarios:
    name: ember-try
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        ember-try-scenario:
         - ember-3.13
         - ember-release
         - ember-beta
         - ember-canary
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 8
    - name: install dependencies
      run: npm ci
    - name: test
      env:
        EMBER_TRY_SCENARIO: ${{ matrix.ember-try-scenario }}
      run: node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO
