name: Documentation Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:

env:
  CI: true

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: install addon dependencies
      working-directory: .
      run: npm ci
    - name: install dependencies
      run: npm ci
    - name: lint js
      run: npm run lint:js
    - name: lint hbs
      run: npm run lint:hbs
    - name: test
      run: npm run test:ember
  percy:
    name: Percy Visual Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: npm
    - name: test
      run: npm run percy-tests
      env:
        PERCY_TOKEN: 263d85e601745ed7aa8c86796e624ea4b0dea18f1405c5f852227af0492b135b
