name: Documentation Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:

env:
  CI: true

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs
    strategy:
      matrix:
        node-version: [ 14.x, 16.x ]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Update to npm@8 for github deps
      run: npm install -g npm@8
    - name: install addon dependencies
      working-directory: .
      run: npm ci
    - name: install dependencies
      run: npm ci
    - name: lint js
      run: npm run lint:js
    - name: lint hbs
      run: npm run lint:hbs
    - name: test
      run: npm run test:ember
      env:
        PERCY_TOKEN: 263d85e601745ed7aa8c86796e624ea4b0dea18f1405c5f852227af0492b135b
