name: Tag Version

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'Semver Release Type (major,minor,patch)'
        required: true

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
          token: ${{ secrets.ZORGBORT_TOKEN }}
    - uses: pnpm/action-setup@v2
    - uses: actions/setup-node@v4
      with:
        node-version: 16
        cache: pnpm
    - name: Validate releaseType
      run: npx in-string-list ${{ github.event.inputs.releaseType }} major,minor,patch
    - name: Setup Git
      run: |
        git config user.name Zorgbort
        git config user.email info@iliosproject.org
    - name: Increment Version
      run: pnpm version --filter ember-simple-charts ${{ github.event.inputs.releaseType }}
    - run: |
        NEW_TAG=`node -p "require('./packages/ember-simple-charts/package.json').version"`
        echo ${NEW_TAG}
        echo "new_tag=${NEW_TAG}" >> $GITHUB_ENV
    - name: Tag Version
      run: |
        git commit -a -m "${{env.new_tag}}"
        git tag ${{env.new_tag}} -m "Tagging the ${{env.new_tag}} ${{ github.event.inputs.releaseType }} release"
    - name: Push Changes
      run: git push --follow-tags
